#!/bin/sh
set -e

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
        set -- apache2-foreground "$@"
fi

echo "**************************************************************************"
echo "Starting webserver at http://localhost:8080"
echo "Note:  any warnings you see after this are safe to ignore if the URL"
echo "works--if not, include this log when posting about errors"
echo ""
echo "This container's internal IP is:  $(hostname --ip-address)"
echo "(Use the internal IP only to connect from other docker containers)"
echo "**************************************************************************"

exec "$@"
